// 3.js-review/2-第一个three.js应用/03-react-three.js/src/App.jsx
import { useState,useEffect } from 'react'
import './App.css'
import * as THREE from "three";

function App() {
useEffect(()=>{
// 导入threejs


// 创建场景
const scene = new THREE.Scene();

// 创建相机
const camera = new THREE.PerspectiveCamera(
  45, // 视角
  window.innerWidth / window.innerHeight, // 宽高比
  0.1, // 近平面
  1000 // 远平面
);
 
// 创建渲染器
const renderer = new THREE.WebGLRenderer();
renderer.setSize(window.innerWidth,window.innerHeight);
document.body.appendChild(renderer.domElement);

// 创建几何体
const geometry = new THREE.BoxGeometry(1,1,1);
// 创建材质
const material = new THREE.MeshBasicMaterial({color:0x00ff00});
// 创建网格
const cube = new THREE.Mesh(geometry,material);

// 将网格添加到场景中
scene.add(cube);

// 设置相机位置
camera.position.z = 5;
camera.lookAt(0,0,0);

// 渲染函数
function animate(){
  requestAnimationFrame(animate); 
  // 旋转
  cube.rotation.x += 0.01;
  cube.rotation.y += 0.01;
  // 渲染
  renderer.render(scene,camera);
}
// 开始渲染
animate();


},[])
  return (
    <>
      <div className='App'>
      
      </div>
    
    </>
  )
}

export default App

// 3.js-review/2-第一个three.js应用/02-vue-three.js/src/App.vue
<script setup>
// 导入threejs
import * as THREE from "three";

// 创建场景
const scene = new THREE.Scene();

// 创建相机
const camera = new THREE.PerspectiveCamera(
  45, // 视角
  window.innerWidth / window.innerHeight, // 宽高比
  0.1, // 近平面
  1000 // 远平面
);
 
// 创建渲染器
const renderer = new THREE.WebGLRenderer();
renderer.setSize(window.innerWidth,window.innerHeight);
document.body.appendChild(renderer.domElement);

// 创建几何体
const geometry = new THREE.BoxGeometry(1,1,1);
// 创建材质
const material = new THREE.MeshBasicMaterial({color:0x00ff00});
// 创建网格
const cube = new THREE.Mesh(geometry,material);

// 将网格添加到场景中
scene.add(cube);

// 设置相机位置
camera.position.z = 5;
camera.lookAt(0,0,0);

// 渲染函数
function animate(){
  requestAnimationFrame(animate); 
  // 旋转
  cube.rotation.x += 0.01;
  cube.rotation.y += 0.01;
  // 渲染
  renderer.render(scene,camera);
}
// 开始渲染
animate();


</script>

<template>
  <div>
   
  </div>
  <HelloWorld msg="Vite + Vue" />
</template>

<style scoped>
*{
  margin: 0;
  padding: 0;
}

html, body{
  width: 100%;
  height: 100%;
  overflow: hidden;
}

canvas{
  display: block;
  position: fixed;
  left: 0;
  top: 0;
  width: 100vw;
  height: 100vh;
}
</style>
